=== TomasQuintao/AutoXML/data/postcards/postcards.dtd
<!ELEMENT postcards (postcard+)>
<!ELEMENT postcard (opening, message)>
<!ATTLIST postcard photo CDATA #IMPLIED>

<!ELEMENT opening (#PCDATA | date | sender | recipient)*>
<!ELEMENT recipient (#PCDATA | name | address)*>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>

<!ELEMENT date (#PCDATA)>
<!ATTLIST date standard CDATA #REQUIRED>

<!ELEMENT message (#PCDATA)>
<!ELEMENT sender (#PCDATA)>

=== TomasQuintao/AutoXML/data/postcards/postcards.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE postais SYSTEM "postcards.dtd">

<postcards>
  <postcard photo="Los Angeles Beach">
    <opening>
      Postcard sent on <date standard="20230531">2023-march-31</date>
      by <sender>Peter Harris</sender> to
      <recipient><name>Alice Smith</name>,
      <address>Liverpool</address></recipient>.
    </opening>
    <message>
      Dear Aunt, weâ€™ve just arrived for the holidays...
      Kisses from your nephew Peter.
    </message>
  </postcard>

  <postcard photo="">
    <opening>
      Postcard from <sender>Peter Kravinsky</sender>, dated <date standard="20200605">05 of June, 2020</date> sent to 
      <recipient><name>Anthony Rogers</name>,
      <address>Brighton</address></recipient>.
    </opening>
    <message>
      Dear Anthony, I strongly recommend you to come here...
      A hug, Peter.
    </message>
  </postcard>
  
  <postcard photo="Himalayas">
    <opening>
      Postcard from <date standard="20200605">26/08/2002</date> by <sender>Thomas Dresden</sender> sent to 
      <recipient><name>Emma Watson</name>,
      <address>Brighton</address></recipient>.
    </opening>
    <message>
      Hey Tony! The view here is otherwordly, you should definitely smell this mountain air.
      Regards, Tom.
    </message>
  </postcard>

   <postcard photo="Paris Eiffel Tower">
    <opening>
      Postcard mailed on <date standard="20210715">July 15, 2021</date>
      by <sender>Margaret Johnson</sender> to
      <recipient><name>Robert Brown</name>,
      <address>Edinburgh</address></recipient>.
    </opening>
    <message>
      Dear Uncle Robert, the city of lights is even more beautiful than they say...
      Love, Maggie.
    </message>
  </postcard>

  <postcard photo="Grand Canyon">
    <opening>
      Postcard from <sender>Daniel Miller</sender>, written <date standard="20220903">3rd Sept 2022</date> to
      <recipient><name>Sarah Wilson</name>,
      <address>Manchester</address></recipient>.
    </opening>
    <message>
      Sarah, you wouldn't believe how massive this canyon is! Photos don't do it justice.
      Cheers, Dan.
    </message>
  </postcard>

  <postcard photo="">
    <opening>
      Postcard sent <date standard="20201122">22-Nov-2020</date>
      by <sender>Emily Clark</sender> to her
      <recipient><name>James Taylor</name>,
      <address>Bristol</address></recipient>.
    </opening>
    <message>
      James, the weather here has been perfect for hiking every single day!
      Best, Em.
    </message>
  </postcard>

  <postcard photo="Sydney Opera House">
    <opening>
      Postcard from <date standard="20230410">10/04/2023</date> by <sender>Andrew White</sender> to
      <recipient><name>Olivia Green</name>,
      <address>Cardiff</address></recipient>.
    </opening>
    <message>
      Olivia, the opera was spectacular last night! Thinking of you.
      Warm regards, Andy.
    </message>
  </postcard>

  <postcard photo="New York Skyline">
    <opening>
      Postcard dated <date standard="20211225">December 25, 2021</date>
      from <sender>Jennifer Lee</sender> to
      <recipient><name>Michael Davis</name>,
      <address>Glasgow</address></recipient>.
    </opening>
    <message>
      Michael, the Christmas lights here are magical! Wish you could see them.
      Love, Jen.
    </message>
  </postcard>

  <postcard photo="">
    <opening>
      Postcard from <sender>Richard Moore</sender>, <date standard="20200814">14 August 2020</date> to
      <recipient><name>Patricia Adams</name>,
      <address>Leeds</address></recipient>.
    </opening>
    <message>
      Patricia, the conference was excellent but I miss home cooking already!
      Yours, Rich.
    </message>
  </postcard>

  <postcard photo="Santorini Sunset">
    <opening>
      Postcard sent on <date standard="20220630">30-06-2022</date>
      by <sender>Sophia Martin</sender> to her
      <recipient><name>William Scott</name>,
      <address>Dublin</address></recipient>.
    </opening>
    <message>
      Will, the sunsets here are like nothing I've ever seen before!
      Missing you, Soph.
    </message>
  </postcard>

  <postcard photo="Swiss Alps">
    <opening>
      Postcard from <date standard="20210220">20/02/2021</date> by <sender>George Walker</sender> to
      <recipient><name>Elizabeth Young</name>,
      <address>Birmingham</address></recipient>.
    </opening>
    <message>
      Dear Liz, the skiing conditions are perfect this year. You'd love it here!
      Best, George.
    </message>
  </postcard>

  <postcard photo="Tokyo Tower">
    <opening>
      Postcard mailed <date standard="20231005">Oct 5, 2023</date>
      from <sender>Kevin Hall</sender> to
      <recipient><name>Amanda King</name>,
      <address>Newcastle</address></recipient>.
    </opening>
    <message>
      Amanda, Tokyo is even more exciting than we imagined! The food is incredible.
      Cheers, Kev.
    </message>
  </postcard>

  <postcard photo="">
    <opening>
      Postcard from <sender>Rachel Wright</sender>, dated <date standard="20210115">15 Jan 2021</date> to
      <recipient><name>Christopher Allen</name>,
      <address>Sheffield</address></recipient>.
    </opening>
    <message>
      Chris, the museum exhibitions here are world class. You'd spend days here!
      Warm wishes, Rachel.
    </message>
  </postcard>

  <postcard photo="Venice Canals">
    <opening>
      Postcard sent <date standard="20220722">22nd July 2022</date>
      by <sender>Benjamin Hill</sender> to his
      <recipient><name>Victoria Cook</name>,
      <address>Nottingham</address></recipient>.
    </opening>
    <message>
      Victoria, gondola rides are as romantic as they say! The city is magical.
      Love, Ben.
    </message>
  </postcard>

  <postcard photo="Rio Carnival">
    <opening>
      Postcard from <date standard="20230218">18/02/2023</date> by <sender>Nicole Bell</sender> to
      <recipient><name>Samuel Ward</name>,
      <address>Southampton</address></recipient>.
    </opening>
    <message>
      Sam, the energy at Carnival is absolutely electric! You'd love the music here.
      Miss you, Nic.
    </message>
  </postcard>

  <postcard photo="African Safari">
    <opening>
      Postcard mailed on <date standard="20220905">September 5, 2022</date>
      from <sender>Timothy Reed</sender> to
      <recipient><name>Diana Baker</name>,
      <address>Portsmouth</address></recipient>.
    </opening>
    <message>
      Diana, we saw lions today! The wildlife here is breathtaking.
      Best, Tim.
    </message>
  </postcard>

  <postcard photo="">
    <opening>
      Postcard from <sender>Laura Cooper</sender>, <date standard="20201110">10-Nov-2020</date> to
      <recipient><name>Henry Evans</name>,
      <address>Oxford</address></recipient>.
    </opening>
    <message>
      Henry, the university library here is absolutely massive! Thought of you immediately.
      Regards, Laura.
    </message>
  </postcard>

  <postcard photo="Great Wall">
    <opening>
      Postcard sent <date standard="20230512">12 May 2023</date>
      by <sender>Jason Morris</sender> to his
      <recipient><name>Rebecca Parker</name>,
      <address>Cambridge</address></recipient>.
    </opening>
    <message>
      Bec, walked 10km on the Wall today! The views are worth every step.
      Love, Jay.
    </message>
  </postcard>

  <postcard photo="Northern Lights">
    <opening>
      Postcard from <date standard="20220315">15/03/2022</date> by <sender>Anna Foster</sender> to
      <recipient><name>Paul Hughes</name>,
      <address>York</address></recipient>.
    </opening>
    <message>
      Paul, the auroras last night were spectacular! Like dancing green ghosts.
      Warmly, Anna.
    </message>
  </postcard>

  <postcard photo="Egypt Pyramids">
    <opening>
      Postcard mailed <date standard="20240105">Jan 5, 2024</date>
      from <sender>Brian Nelson</sender> to
      <recipient><name>Karen Carter</name>,
      <address>Plymouth</address></recipient>.
    </opening>
    <message>
      Karen, the pyramids are even more impressive in person! The heat takes getting used to though.
      Cheers, Brian.
    </message>
  </postcard>

  <postcard photo="">
    <opening>
      Postcard from <sender>Christine Mitchell</sender>, dated <date standard="20211210">10 Dec 2021</date> to
      <recipient><name>Steven Collins</name>,
      <address>Norwich</address></recipient>.
    </opening>
    <message>
      Steve, the Christmas markets here are wonderful! The mulled wine is keeping me warm.
      Love, Chris.
    </message>
  </postcard>

  <postcard photo="Amazon Rainforest">
    <opening>
      Postcard sent on <date standard="20220808">08-Aug-2022</date>
      by <sender>Patrick Stewart</sender> to his
      <recipient><name>Janet Price</name>,
      <address>Brighton</address></recipient>.
    </opening>
    <message>
      Janet, the biodiversity here is incredible! Saw monkeys and toucans today.
      Best, Pat.
    </message>
  </postcard>

  <postcard photo="Dubai Skyline">
    <opening>
      Postcard from <date standard="20230228">28 Feb 2023</date> by <sender>Emma Richardson</sender> to
      <recipient><name>Mark Bennett</name>,
      <address>Belfast</address></recipient>.
    </opening>
    <message>
      Mark, the Burj Khalifa is even taller than I imagined! The view is worth the elevator ride.
      Warm wishes, Emma.
    </message>
  </postcard>
  
    <postcard photo="Berlin Office">
    <opening>
      Postcard sent on <date standard="20230912">12-Sept-2023</date>
      by <sender>Jonathan Myers</sender> to
      <recipient><name>Sarah Connor</name>,
      <address>London</address></recipient>.
    </opening>
    <message>
      Sarah, the client meeting went better than expected. They approved phase two! 
      Will debrief when I'm back Thursday. - Jon
    </message>
  </postcard>

  <postcard photo="">
    <opening>
